### ISSUE TITLE
Returning to main site from interactive

### ISSUE THREAD

**Issue by C-Marquet** [sacdallago/embed.predictprotein.org#25]
atm if i click back on my browser i just get back to the start page and have to submit the sequence again to see the main predictions, maybe add a return button or sth?

**Comment by sacdallago** [comment]
Note to self: state transitions

**Comment by sacdallago** [comment]
Log (tried to get to this for about 2h):
- Need to change from constructor to function (e.g. useHook)
- useHook triggers UI update constnatly --> stream of fetch requests
- every fetch requests triggers scroll-to-top, very disruptive
- need to fetch separately structure and annotations, otherwise update from one triggers update for the other and infinite loop starts
- structure depends on annotations for color overlay, so not as easy to disentangle
- could use store to store features and get rid of coupling in structure component but requires significant rewrite of the entire store architecture
